apiVersion: v1
entries:
  temporal:
  - apiVersion: v2
    appVersion: 1.23.0
    created: "2024-03-29T18:25:30.355544+02:00"
    dependencies:
    - condition: cassandra.enabled
      name: cassandra
      repository: https://charts.helm.sh/incubator
      version: 0.14.3
    - condition: prometheus.enabled
      name: prometheus
      repository: https://prometheus-community.github.io/helm-charts
      version: 15.1.3
    - condition: elasticsearch.enabled
      name: elasticsearch
      repository: https://helm.elastic.co
      version: 7.17.3
    - condition: grafana.enabled
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 5.0.10
    description: Temporal is a distributed, scalable, durable, and highly available
      orchestration engine to execute asynchronous long-running business logic in
      a scalable and resilient way.
    digest: 5c2631389dc94dfd86666b146cec56206a6b8f14af759584c542cad6f6f0d8b3
    home: https://temporal.io/
    keywords:
    - temporal
    - workflow
    - orchestration
    maintainers:
    - name: Temporal Technologies Inc.
      url: https://temporal.io/
    name: temporal
    sources:
    - https://github.com/temporalio/temporal
    type: application
    urls:
    - https://fairmoney.github.io/temporal-helm-charts/temporal-0.36.0.tgz
    version: 0.36.0
generated: "2024-03-29T18:25:30.347138+02:00"
